-- 1. Feedback Approval
ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS is_approved BOOLEAN DEFAULT FALSE;

-- 2. Banner Management
CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  title TEXT,
  subtitle TEXT,
  link TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
